
DROP DATABASE IF EXISTS OnlineBookSystem;
  CREATE DATABASE OnlineBookSystem;
  USE OnlineBookSystem;

  CREATE TABLE Events (
    EventID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EventDesc VARCHAR(100) NOT NULL,
    EventDate VARCHAR(25) NOT NULL,
    EventLocation VARCHAR(25) NOT NULL
  );

  CREATE TABLE Registrants (
    RegID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL
  );

  CREATE TABLE Bookings (
    BookID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EventID INT NOT NULL,
    RegID INT NOT NULL,
    FOREIGN KEY (EventID) REFERENCES Events(EventID),
    FOREIGN KEY (RegID) REFERENCES Registrants(RegID)
  );

SHOW TABLES;
SHOW COLUMNS FROM Events;
SHOW COLUMNS FROM Bookings;
SHOW COLUMNS FROM Registrants;
